
name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
#          - windows-latest
        ocaml-version:
          - 4.10.0
        skip_test:
          - false

        include:
          - ocaml-version: 4.05.0
            os: ubuntu-latest
            skip_test: true


    env:
      SKIP_TEST: ${{ matrix.skip_test }}
      OCAML_VERSION: ${{ matrix.ocaml-version }}
      OS: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.opam
          key: ${{ runner.os }}-drom-opam-cache-${{ hashFiles('*.opam') }}
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com

      - run: opam depext -y ./*.opam

      - run: opam install -y ./*.opam --deps-only --with-test

      - run: opam exec -- dune build @install

      - name: run test suite
        run: opam exec -- dune build @runtest
        if: env.SKIP_TEST != 'true'

      - name: test source is well formatted
        run: opam exec -- dune build @fmt
        continue-on-error: true
        if: env.OCAML_VERSION == '4.10.0' && env.OS == 'ubuntu-latest'
